name: kateri
description: Antigenic Map Viewer
version: 0.1.0
homepage: https://antigenic-cartography.org

environment:
  sdk: '>=2.16.2 <3.0.0'

executables:
  kateri: kateri

dev_dependencies:
  lints: ^1.0.0
  flutter_lints: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.7.3
  path_provider: ^2.0.9
  intl: ^0.17.0
  universal_platform: ^1.0.0+1
  typed_data: ^1.3.0
  window_manager: ^0.2.3
  # side_navigation: ^1.0.2

  # open ace file
  file_picker: ^4.5.1

  # exportPdf
  file_saver: ^0.1.0
  brotli: ^0.5.0
  args: ^2.3.0
  accordion: ^2.5.1

flutter:
  uses-material-design: true
