name: kateri
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

executables:
  kateri: kateri

dev_dependencies:
  lints: ^1.0.0
  flutter_lints: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.7.3
  path_provider: ^2.0.9

flutter:
  uses-material-design: true
